NbaEcommerce/Controllers/CarrelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NbaEcommerce.Models;

namespace NbaEcommerce.Controllers
{
    public class CarrelloController : Controller
    {
        private readonly NbaStoreContext _context;

        public CarrelloController(NbaStoreContext context)
        {
            _context = context;
        }

        // GET: Dispositivo
        public async Task<IActionResult> Index()
        {
            List<Prodotto> listaProdotti = new List<Prodotto>();

            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                List<string> listaId = listaIdProdotti.Select(x => x.Id).ToList();
                listaProdotti = await _context.Prodotto.Include(p => p.IdCategoriaNavigation)
                                    .Include(p => p.IdMarchioNavigation)
                                    .Include(p => p.IdDispositivoNavigation)
                                    .Include(p => p.Immagine)
                                    .Where(x => listaId.Contains(x.Id.ToString())).ToListAsync();
            }

            return View(listaProdotti);
        }

        // GET: Dispositivo
        public IActionResult EliminaProdotto(Guid Id)
        {
            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                var prodotto = listaIdProdotti.Where(x => x.Id == Id.ToString()).First();
                listaIdProdotti.Remove(prodotto);

                HttpContext.Session.SetObject(Utility.Utility._KeyCarrello, listaIdProdotti);
            }

            return RedirectToAction("Index");
        }

        public ActionResult AggiornaQuantita(string idprodotto, string quantita)
        {
            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                carrelloProdotto prodotto = listaIdProdotti.Where(x => x.Id == idprodotto.ToString()).FirstOrDefault();

                if (prodotto != null && !String.IsNullOrEmpty(prodotto.Id))
                {
                    int indexProdotto = listaIdProdotti.IndexOf(prodotto);
                    //rimuovo il prodotto, lo modifico e lo reinserisco nella lista.
                    listaIdProdotti.Remove(prodotto);

                    prodotto.Quantita = int.Parse(quantita);

                    listaIdProdotti.Insert(indexProdotto, prodotto);

                    HttpContext.Session.SetObject(Utility.Utility._KeyCarrello, listaIdProdotti);
                }
            }
            return new JsonResult(String.Empty);
        }

        public IActionResult CreaOrdine()
        {
            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                double costoTotale = 0;
                foreach (carrelloProdotto item in listaIdProdotti)
                {
                    double prezzoVendita = _context.Prodotto.Where(x => x.Id == new Guid(item.Id)).Select(x => x.PrezzoVendita).FirstOrDefault();
                    var costoProdotto = item.Quantita * prezzoVendita;
                    costoTotale = costoTotale + costoProdotto;
                }

                //creo l'ordine
                Guid idOrdine =Guid.NewGuid();
                OrdineCliente ordineCliente = new OrdineCliente()
                {
                    Id = idOrdine,
                    IdCliente = new Guid("c413dc21-af58-4a5c-8ff4-bf43e4a4d782"),
                    DataInserimento = DateTime.Now,
                    DataModifica = DateTime.Now,
                    UtenteInserimento = HttpContext.User.Identity.Name,
                    UtenteModifica = HttpContext.User.Identity.Name,
                    Spedito = false,
                    SpeditoInParte = false,
                    DataConsegna = DateTime.Now.AddMonths(1),
                    Note = string.Empty,
                    Pagato = false,
                    PrezzoOrdine = costoTotale
                };

                _context.OrdineCliente.Add(ordineCliente);
                _context.SaveChanges();

                foreach (carrelloProdotto prodotto in listaIdProdotti)
                {
                    RigaOrdineCliente rigaOrdineCliente = new RigaOrdineCliente()
                    {
                        Id = new Guid(),
                        IdOrdine = idOrdine,
                        Quantita = prodotto.Quantita,
                        IdProdotto = new Guid(prodotto.Id),
                        DataInserimento = DateTime.Now,
                        DataModifica = DateTime.Now,
                        UtenteInserimento = HttpContext.User.Identity.Name,
                        UtenteModifica = HttpContext.User.Identity.Name,
                        Spedito = false
                    };

                    _context.RigaOrdineCliente.Add(rigaOrdineCliente);
                    _context.SaveChanges();
                }

            }

            return RedirectToAction("Index");
        }

        public JsonResult IsCarrelloEmpty()
        {
            bool result = false;

            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                if (listaIdProdotti != null && listaIdProdotti.Count > 0)
                {
                    result = true;
                }

            }

            return new JsonResult(result);
        }
    }
}

NbaEcommerce/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NbaEcommerce.Models;

namespace NbaEcommerce.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly NbaStoreContext _context;

        public CategoriaController(NbaStoreContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categoria.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descrizione,Attivo")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                categoria.Id = Guid.NewGuid();
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Descrizione,Attivo")] Categoria categoria)
        {
            if (id != categoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var categoria = await _context.Categoria.FindAsync(id);
            _context.Categoria.Remove(categoria);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(Guid id)
        {
            return _context.Categoria.Any(e => e.Id == id);
        }
    }
}

NbaEcommerce/Controllers/MarchioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NbaEcommerce.Models;

namespace NbaEcommerce.Controllers
{
    public class MarchioController : Controller
    {
        private readonly NbaStoreContext _context;

        public MarchioController(NbaStoreContext context)
        {
            _context = context;
        }

        // GET: Marchio
        public async Task<IActionResult> Index()
        {
            return View(await _context.Marchio.ToListAsync());
        }

        // GET: Marchio/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marchio = await _context.Marchio
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marchio == null)
            {
                return NotFound();
            }

            return View(marchio);
        }

        // GET: Marchio/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Marchio/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Descrizione,Attivo")] Marchio marchio)
        {
            if (ModelState.IsValid)
            {
                marchio.Id = Guid.NewGuid();
                _context.Add(marchio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(marchio);
        }

        // GET: Marchio/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marchio = await _context.Marchio.FindAsync(id);
            if (marchio == null)
            {
                return NotFound();
            }
            return View(marchio);
        }

        // POST: Marchio/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Descrizione,Attivo")] Marchio marchio)
        {
            if (id != marchio.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(marchio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarchioExists(marchio.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(marchio);
        }

        // GET: Marchio/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var marchio = await _context.Marchio
                .FirstOrDefaultAsync(m => m.Id == id);
            if (marchio == null)
            {
                return NotFound();
            }

            return View(marchio);
        }

        // POST: Marchio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var marchio = await _context.Marchio.FindAsync(id);
            _context.Marchio.Remove(marchio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarchioExists(Guid id)
        {
            return _context.Marchio.Any(e => e.Id == id);
        }
    }
}

NbaEcommerce/Views/Shared/_Footer.cshtml
<div class="mt-5 py-4 small text-dark footer-primary" >
    <div class="container ">
        <div class="row">
            <div class="col-4">
                <h6>Trovaci su</h6>

                <a href="#" class="h4 text-dark" title="Facebook">
                    <i class="fab fa-facebook-square"></i>
                </a>

                <a href="#" class="h4 text-dark" title="Instagram">
                    <i class="fab fa-instagram"></i>
                </a>
            </div>


            <div class="col-4 text-center">
                <a class="navbar-brand text-dark" href="#">
                    <img src="~/images/logo.png" style="width:50px;height:50px" />
                    <br />
                    Tech Spare Parts
                </a>
            </div>

            <div class="col-4 text-right">
                <h6>Aiuto e informazioni</h6>

                <a href="#" class="text-dark" title="Facebook">
                    Resi
                </a>
                <br />
                <a href="#" class="text-dark" title="Instagram">
                    Spedizioni
                </a>
                <br />
                <a href="#" class="text-dark" title="Instagram">
                    Pagamenti
                </a>
            </div>
        </div>
    </div>
</div>
<div class="bg-secondary mt-0 py-3 small footer-secondary">
    <div class="container">
        <span class="text-white float-left">@@2019 NBA Tech Spare Parts</span>
        <span class="text-white float-right">Informativa privacy | cookies</span>
    </div>
</div>

NbaEcommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NbaEcommerce</title>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/dist/main.bundle.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <span class="h5 text-warning">Admin</span>&nbsp;<img src="~/images/logo.png" style="width:50px;height:50px" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Prodotto" asp-action="Index">
                                Prodotti
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Marchio" asp-action="Index">
                                Marchi
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Categoria" asp-action="Index">
                                Categorie
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Dispositivo" asp-action="Index">
                                Dispositivo
                            </a>
                        </li>
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </nav>
    </header>

    <div class="container mb-5">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    @RenderSection("Scripts", required: false)
</body>

</html>

NbaEcommerce/Views/Shared/_LayoutCliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NbaEcommerce</title>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/dist/main.bundle.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="~/images/logo.png" style="width:50px;height:50px" />
                </a>

                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="itemCatalogoCliente" asp-controller="Home" asp-action="Index">
                                Azienda
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="itemCatalogoCliente" asp-controller="Prodotto" asp-action="IndexCliente">
                                Catalogo online
                            </a>

                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form class="form-inline my-2 my-lg-0">
                                <a asp-controller="Carrello" asp-action="Index" class="nav-link text-dark">
                                    <i class="fas fa-shopping-cart"></i>
                                </a>
                                <span id="spanBadgeCart" class="badge badge-pill badge-danger" style="display:none;margin-left:-15px;margin-bottom: 10px;font-size:40%!important">&nbsp;</span>
                            </form>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid mt-3 mb-5">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <partial name="_Footer" />

    @RenderSection("Scripts", required: false)
</body>
</html>

NbaEcommerce/Views/Shared/_LayoutRegister.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NbaEcommerce</title>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/dist/main.bundle.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body class="bg-light">


    <div class="container-fluid mt-3 mb-5">
        <partial name="_CookieConsentPartial" />

        <div class="row justify-content-center mb-5">
            <div class="col col-md-4">
                <div class="text-center ">
                    <a asp-action="Index" asp-controller="Home">

                        <img src="~/images/logo.png" class="img-fluid d-block mx-auto" style="max-height:100px; max-width:100px;" />
                    </a>
                    <br />
                    <span class="text-secondary text-uppercase" style="font-size:20px;font-weight:100">Tech Spare Parts</span>
                </div>
            </div>
        </div>

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="bg-secondary mt-0 py-3 small footer-secondary" style="margin-top:300px !important;">
        <div class="container">
            <span class="text-white float-left">@@2019 NBA Tech Spare Parts</span>
            <span class="text-white float-right">Informativa privacy | cookies</span>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>