NbaEcommerce/Controllers/CarrelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NbaEcommerce.Models;

namespace NbaEcommerce.Controllers
{
    public class CarrelloController : Controller
    {
        private readonly NbaStoreContext _context;

        public CarrelloController(NbaStoreContext context)
        {
            _context = context;
        }

        // GET: Dispositivo
        public async Task<IActionResult> Index()
        {
            List<Prodotto> listaProdotti = new List<Prodotto>();

            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                List<string> listaId = listaIdProdotti.Select(x => x.Id).ToList();
                listaProdotti = await _context.Prodotto.Include(p => p.IdCategoriaNavigation)
                                    .Include(p => p.IdMarchioNavigation)
                                    .Include(p => p.IdDispositivoNavigation)
                                    .Include(p => p.Immagine)
                                    .Where(x => listaId.Contains(x.Id.ToString())).ToListAsync();
            }

            return View(listaProdotti);
        }

        // GET: Dispositivo
        public IActionResult EliminaProdotto(Guid Id)
        {
            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                var prodotto = listaIdProdotti.Where(x => x.Id == Id.ToString()).First();
                listaIdProdotti.Remove(prodotto);

                HttpContext.Session.SetObject(Utility.Utility._KeyCarrello, listaIdProdotti);
            }

            return RedirectToAction("Index");
        }

        public ActionResult AggiornaQuantita(string idprodotto, string quantita)
        {
            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                carrelloProdotto prodotto = listaIdProdotti.Where(x => x.Id == idprodotto.ToString()).FirstOrDefault();

                if (prodotto != null && !String.IsNullOrEmpty(prodotto.Id))
                {
                    int indexProdotto = listaIdProdotti.IndexOf(prodotto);
                    //rimuovo il prodotto, lo modifico e lo reinserisco nella lista.
                    listaIdProdotti.Remove(prodotto);

                    prodotto.Quantita = int.Parse(quantita);

                    listaIdProdotti.Insert(indexProdotto, prodotto);

                    HttpContext.Session.SetObject(Utility.Utility._KeyCarrello, listaIdProdotti);
                }
            }
            return new JsonResult(String.Empty);
        }

        public IActionResult CreaOrdine()
        {
            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                double costoTotale = 0;
                foreach (carrelloProdotto item in listaIdProdotti)
                {
                    double prezzoVendita = _context.Prodotto.Where(x => x.Id == new Guid(item.Id)).Select(x => x.PrezzoVendita).FirstOrDefault();
                    var costoProdotto = item.Quantita * prezzoVendita;
                    costoTotale = costoTotale + costoProdotto;
                }

                //creo l'ordine
                Guid idOrdine =Guid.NewGuid();
                OrdineCliente ordineCliente = new OrdineCliente()
                {
                    Id = idOrdine,
                    IdCliente = new Guid("c413dc21-af58-4a5c-8ff4-bf43e4a4d782"),
                    DataInserimento = DateTime.Now,
                    DataModifica = DateTime.Now,
                    UtenteInserimento = HttpContext.User.Identity.Name,
                    UtenteModifica = HttpContext.User.Identity.Name,
                    Spedito = false,
                    SpeditoInParte = false,
                    DataConsegna = DateTime.Now.AddMonths(1),
                    Note = string.Empty,
                    Pagato = false,
                    PrezzoOrdine = costoTotale
                };

                _context.OrdineCliente.Add(ordineCliente);
                _context.SaveChanges();

                foreach (carrelloProdotto prodotto in listaIdProdotti)
                {
                    RigaOrdineCliente rigaOrdineCliente = new RigaOrdineCliente()
                    {
                        Id = new Guid(),
                        IdOrdine = idOrdine,
                        Quantita = prodotto.Quantita,
                        IdProdotto = new Guid(prodotto.Id),
                        DataInserimento = DateTime.Now,
                        DataModifica = DateTime.Now,
                        UtenteInserimento = HttpContext.User.Identity.Name,
                        UtenteModifica = HttpContext.User.Identity.Name,
                        Spedito = false
                    };

                    _context.RigaOrdineCliente.Add(rigaOrdineCliente);
                    _context.SaveChanges();
                }

            }

            return RedirectToAction("Index");
        }

        public JsonResult IsCarrelloEmpty()
        {
            bool result = false;

            //ottengo l'oggetto attualmente salvato in sessione.
            List<carrelloProdotto> listaIdProdotti = new List<carrelloProdotto>();

            if (HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello) != null)
            {
                listaIdProdotti = HttpContext.Session.GetObject<List<carrelloProdotto>>(Utility.Utility._KeyCarrello);

                if (listaIdProdotti != null && listaIdProdotti.Count > 0)
                {
                    result = true;
                }

            }

            return new JsonResult(result);
        }
    }
}

NbaEcommerce/Controllers/ProdottoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NbaEcommerce.Models;
//using NbaEcommerce.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NbaEcommerce.Controllers
{
    public class ProdottoController : Controller
    {
        private readonly NbaStoreContext _context;

        public ProdottoController(NbaStoreContext context)
        {
            _context = context;
        }

        // GET: Prodotto
        public async Task<IActionResult> Index(string marchio, string categoria)
        {
            ViewData["marchio"] = marchio;
            ViewData["categoria"] = categoria;

            var nbaStoreContext = _context.Prodotto
                                    .Include(p => p.IdCategoriaNavigation)
                                    .Include(p => p.IdMarchioNavigation)
                                    .Include(p => p.IdDispositivoNavigation)
                                    .Where(x => (string.IsNullOrEmpty(marchio) || x.IdMarchioNavigation.Descrizione.Contains(marchio)) & (string.IsNullOrEmpty(categoria) || x.IdCategoriaNavigation.Descrizione.Contains(categoria)));
            return View(await nbaStoreContext.ToListAsync());
        }

        public async Task<IActionResult> IndexCliente()
        {
            ViewData["categorie"] = await _context.Categoria.ToListAsync();
            ViewData["marchi"] = await _context.Marchio.ToListAsync();
            ViewData["dispositivi"] = await _context.Dispositivo.ToListAsync();

            ViewData["marchioSelezionato"] = null;
            ViewData["categoriaSelezionata"] = null;
            ViewData["dispositivoSelezionato"] = null;

            List<Prodotto> listaProdotti = await _context.Prodotto.
                                    Include(p => p.IdCategoriaNavigation)
                                    .Include(p => p.IdMarchioNavigation)
                                    .Include(p => p.IdDispositivoNavigation)
                                    .Include(p => p.Immagine).ToListAsync();
            return View(listaProdotti);
        }


        [HttpPost]
        public async Task<IActionResult> IndexCliente(Guid? marchio, Guid? categoria, Guid? dispositivo)
        {
            ViewData["categorie"] = await _context.Categoria.ToListAsync();
            ViewData["marchi"] = await _context.Marchio.ToListAsync();
            ViewData["dispositivi"] = await _context.Dispositivo.ToListAsync();

            List<Prodotto> listaProdotti = await _context.Prodotto
                                    .Include(p => p.IdCategoriaNavigation)
                                    .Include(p => p.IdMarchioNavigation)
                                    .Include(p => p.IdDispositivoNavigation)
                                    .Include(p => p.Immagine)
                                    .Where(x => (marchio == null || x.IdMarchio == marchio) & (dispositivo == null || dispositivo == x.IdDispositivo) & (categoria == null || x.IdCategoria == categoria)).ToListAsync();

            ViewData["dispositivoSelezionato"] = dispositivo;
            ViewData["categoriaSelezionata"] = categoria;
            ViewData["marchioSelezionato"] = marchio;

            return View(listaProdotti);

            //String[] arrayMarchiSelezionati = new string[0];
            //String[] arrayCategorieSelezionati = new string[0];
            //String[] arrayDispositiviSelezionati = new string[0];

            //List<ViewProdottoViewModel> nbaStoreContext = new List<ViewProdottoViewModel>();

            //if (listaMarchi != null)
            //{
            //    arrayMarchiSelezionati = listaMarchi?.Split(";");
            //    ViewData["dispositivi"] = await _context.Dispositivo.Where(x => arrayMarchiSelezionati.Contains(x.IdMarchio.ToString())).ToListAsync();
            //}

            ////if (listaCategorie != null)
            ////{
            ////    arrayCategorieSelezionati = listaCategorie?.Split(";");

            ////}

            //if (listaDispositivi != null)
            //{
            //    arrayDispositiviSelezionati = listaDispositivi?.Split(";");
            //}

            //nbaStoreContext = await _context.ViewProdotto.Where(x => (arrayCategorieSelezionati.Length == 0 | arrayCategorieSelezionati.Contains(x.IdCategoria.ToString())) & (arrayMarchiSelezionati.Length == 0 | arrayMarchiSelezionati.Contains(x.IdMarchio.ToString()))).ToListAsync();



            //return View(nbaStoreContext);
        }


        // GET: Prodotto/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodotto = await _context.Prodotto
                .Include(p => p.IdCategoriaNavigation)
                .Include(p => p.IdMarchioNavigation)
                .Include(p => p.IdDispositivoNavigation)
                .Include(p => p.Immagine)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (prodotto == null)
            {
                return NotFound();
            }

            return View(prodotto);
        }

        // GET: Prodotto/Create
        public IActionResult Create()
        {
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "Id", "Descrizione");
            ViewData["IdMarchio"] = new SelectList(_context.Marchio, "Id", "Descrizione");
            ViewData["IdDispositivo"] = new SelectList(_context.Dispositivo, "Id", "Descrizione");

            return View();
        }

        // POST: Prodotto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdMarchio,IdCategoria,IdDispositivo,Titolo,Descrizione,PrezzoVendita,PrezzoAcquisto,Attivo,Quantità")] Prodotto prodotto, List<IFormFile> immagini)
        {
            if (ModelState.IsValid)
            {
                prodotto.Id = Guid.NewGuid();
                _context.Add(prodotto);
                await _context.SaveChangesAsync();

                // full path to file in temp location
                var filePath = Path.GetTempFileName();

                foreach (IFormFile formFile in immagini)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        await formFile.CopyToAsync(memoryStream);
                        Immagine img = new Immagine { Id = Guid.NewGuid(), IdProdotto = prodotto.Id, ImageInfo = formFile.FileName, Data = memoryStream.ToArray() };
                        _context.Immagine.Add(img);
                        await _context.SaveChangesAsync();
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "Id", "Descrizione", prodotto.IdCategoria);
            ViewData["IdMarchio"] = new SelectList(_context.Marchio, "Id", "Descrizione", prodotto.IdMarchio);
            ViewData["IdDispositivo"] = new SelectList(_context.Dispositivo, "Id", "Descrizione", prodotto.IdDispositivo);

            return View(prodotto);
        }

        // GET: Prodotto/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prodotto = await _context.Prodotto.FindAsync(id);
            if (prodotto == null)
            {
                return NotFound();
            }
            ViewData["IdCategoria"] = new SelectList(_context.Categoria, "Id", "Descrizione", prodotto.IdCategoria);
            ViewData["IdMarchio"] = new SelectList(_context.Marchio, "Id", "Descrizione", prodotto.IdMarchio);
            ViewData["IdDispositivo"] = new SelectList(_context.Dispositivo, "Id", "Descrizione", prodotto.IdDispositivo);

            return View(prodotto);
        }

        // POST: Prodotto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,IdMarchio,IdCategoria,IdDispositivo,Titolo,Descrizione,PrezzoVendita,PrezzoAcquisto,Attivo,Quantità")] Prodotto prodotto, List<IFormFile> immagini)
        {
            if (id != prodotto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //rimuovo tutte le immagini
                    List<Immagine> listaImmaginiAttuali = await _context.Immagine.Where(x => x.IdProdotto == prodotto.Id).ToListAsync();
                    foreach (var item in listaImmaginiAttuali)
                    {
                        _context.Immagine.Remove(item);
                        await _context.SaveChangesAsync();
                    }

                    //Modifico il prodotto
                    _context.Update(prodotto);
                    await _context.SaveChangesAsync();

                    //Inserisco le immagini
                    var filePath = Path.GetTempFileName();

                    foreach (IFormFile formFile in immagini)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await formFile.CopyToAsync(memoryStream);
                            Immagine img = new Immagine { Id = Guid.NewGuid(), IdProdotto = prodotto.Id, Data = memoryStream.ToArray() };

NbaEcommerce/Views/Carrello/Index.cshtml
@model IEnumerable<NbaEcommerce.Models.Prodotto>

@{
    ViewData["Title"] = "Il mio carrello";
}

<script src="https://www.paypal.com/sdk/js?client-id=sb"></script>

<div class="row mt-2">
    <div class="col-6">
        <h2>@ViewData["Title"] </h2>
    </div>

    @if (Model.Count() > 0)
    {
        <div class="col-6">
            <a asp-action="IndexCliente" asp-controller="Prodotto" class="btn btn-outline-dark float-right mt-2">Continua con gli acquisti</a>
        </div>

    }
</div>
<hr />


@if (Model.Count() > 0)
{
    <div class="row">

        <div class="col-md-4 col-sm-6 offset-md-2 col-xs-12 mb-4">
            <div class="card border-left-primary shadow">
                <div class="card-body">
                    <h4>Articoli</h4>

                    @foreach (Prodotto prodotto in Model)
                    {

                        var base64 = Convert.ToBase64String(prodotto.Immagine.First().Data);
                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                        <hr />
                        <div class="row">
                            <div class="col-5">
                                <img src="@imgSrc" style=" cursor: pointer;" class="img-fluid" />
                            </div>
                            <div class="col-5">
                                <h4 class="mt-4">
                                    <strong>@prodotto.PrezzoVendita €</strong>
                                    <br />
                                    <small>@prodotto.Descrizione</small>
                                </h4>

                                <label>Quanità</label>
                                <select data-costo="@prodotto.PrezzoVendita" class="form-control form-control-sm select-prodotto" data-idProdotto="@prodotto.Id" onchange="aggiornaQuantita(this, '@Url.Action("AggiornaQuantita", "Carrello")')">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                </select>

                            </div>
                            <div class="col-2">
                                <a class="text-secondary" asp-controller="Carrello" asp-action="EliminaProdotto" asp-route-id="@prodotto.Id"> <i class="fas fa-times"></i> </a>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>

        @{
            List<Prodotto> listaProdotti = Model.ToList();
        }

        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="card border-left-primary shadow">
                <div class="card-body">
                    <div class="row">
                        <div class="col-12 mb-2">
                            <h4>Pagamento</h4>
                            <hr />


                            <span class="float-left">Totale parziale</span>
                            <span class="float-right">
                                @{

                                    <strong id="lblTotale">@listaProdotti.Sum(x => x.PrezzoVendita) €</strong>
                                }
                            </span>
                        </div>

                        <div class="col-12 mb-2">
                            <span class="float-left">Spedizione</span>
                            <span class="float-right">
                                @{

                                    <strong>Gratuita</strong>
                                }
                            </span>
                        </div>

                        <div class="col-12 mb-2 border-top">
                            <span class="float-left  mt-4">Totale Ordine</span>
                            <span class="float-right  mt-4">
                                @{

                                    <strong>@listaProdotti.Sum(x => x.PrezzoVendita) €</strong>
                                }
                            </span>
                        </div>


                        @if (User.IsInRole("Utente"))
                        {
                            <a asp-controller="Carrello" asp-action="CreaOrdine" class="btn btn-primary btn-sm">Paga test</a>

                            <div id="divPayment" class="mt-5 col-8 offset-2">

                            </div>

                        }
                        else
                        {
                            <div class="mt-5 col-8 offset-2">
                                <a asp-area="Identity" class="btn btn-primary btn-block btn-lg" asp-page="/Account/Login">Accedi per proseguire</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row justify-content-center">
        <div class="col-12 text-center">
            <h1>Il tuo carrello è vuoto!</h1>
            <a asp-action="IndexCliente" asp-controller="Prodotto" class="btn btn-outline-dark mt-2">Inzia a fare acquisti</a>
        </div>
    </div>
}





@**@
<script>paypal.Buttons().render('#divPayment');</script>